import { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'

// Styles
import styles from '../styles/Home.module.css'

// Constants
import { apiURL } from '../constants/url'

// Components
import { CountryCard } from '../components/country/card'

// Types
import { ICountry } from '../types/interfaces'
type Props = {
  allCountries: ICountry[]
}

export const getStaticProps: GetStaticProps = async () => {

  const allCountries = await (await fetch(`${apiURL}/all`)).json() as ICountry[]
  
  return {
    props: {
      allCountries
    }
  }

}

const Home: NextPage<Props> = ({ allCountries }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        { allCountries.map(country => {
          return <CountryCard
                  key={country.name.common}
                  name={country.name.common}
                  population={country.population}
                  region={country.region}
                  capital={country.capital}
                  img={country.flags.svg}
                  />
        }) }
      </main>
    </div>
  )
}

export default Home
